### ISSUE TITLE
Remove towel thing from awesomo shipyaoi command

### ISSUE THREAD

**Issue by Dragon1320** [feinwarusoftware/sppd#100]
He wont stop complaining about it, anyway, wasn't someone supposed to have removed it already?

**Comment by iTweeno** [comment]
the pull request is in awesomo

**Comment by Dragon1320** [comment]
@iTweeno theres no pull request mate
![image](https://user-images.githubusercontent.com/18635887/64083388-38a83380-cd17-11e9-9080-22709dea31e0.png)

**Comment by iTweeno** [comment]
it was

**Comment by Dragon1320** [comment]
apparently its been removed... until it comes back to haunt us once again
