### ISSUE TITLE
Google analytics console error on adblock

### ISSUE THREAD

**Issue by Dragon1320** [feinwarusoftware/sppd#104]
Instead of an incomprehensible error, print a useful console log asking the user to whitelist us on adblock to support us (cos we dont use ads anyway).

The current error message causes issues on lighthouse (in best practices).

**Comment by Dragon1320** [comment]
This seems to be an error on chrome and a warning on firefox? If that is correct it might be due to different adblock plugins.

**Comment by MattheousDT** [comment]
Lighthouse should only be used in incognito as recommended by Google.
