### ISSUE TITLE
Medicine Woman Sharon's description has (Heals Leader for Undefined Health)

### ISSUE THREAD

**Issue by iTweeno** [feinwarusoftware/sppd#111]
*Please state which of the following this bug report related to:*
- API

## Bug Description
Medicine Woman Sharon's description has (Heals Leader for Undefined Health)

**Comment by Dragon1320** [comment]
Technically the new issue is a duplicate of this but that one has a better description so ill mark this one a dupe.

Other issue: https://github.com/feinwarusoftware/sppd/issues/127
