### ISSUE TITLE
Some bugs and wrong info.

### ISSUE THREAD

**Issue by MaskedRoninTTV** [feinwarusoftware/sppd#113]
Hey guys i've already talked to Mattheous on Discord and he suggested i write down the bugs here.
I never used this site or know anything about programming so i'm not really sure about what to do with all the instructions here below. I've been fixing the info from SPPD Stats (Card stats) for our team and i've also been checking the info on your site and i noticed some wrong info. Because i've been fixing a lot of stats i'm not sure for which cards the wrong info was on your site or SPPD Stats. Since the bot uses info from the site it probably means the things that are wrong are on the site itself. Anyway here are the things i noticed.

1. A lot if not all of spells and traps on your site have entries for level 3 twice and it's missing info for level 7. (Might also be the problem with some other cards)

2. If you open your website from Google searches it doesn't load the page as it should. This is the site that gets opened: https://sppd.feinwaru.com/?hl=en
If you delete the "/?hl=en" it works correctly.

3. I think that stats for Mosquito Swarm and Auto-Vacuum are wrong.

4. A lot of information is missing and some information is static. Here are a few examples so you see what i mean:

- Captain Wendy, her power range gets increased with upgrades. She starts with power range 4, which is stated on your site as radius 2, which is correct, but at level 7 her power range is 4.8. Your site and bot always say that her power radius is 2, no matter the upgrade.

- Warboy Tweek, same problem. He starts with Warcry: 2-4 second speed boost and at level 7 ends up with 2.4-4.4, your site and bot always say it's 2-4.

- There are a lot of examples where info is wrong/static, mostly with powers that can damage units and leader. President Garrison at level 1 deals 220 damage to a unit or 10% of that to the leader, which is 22. But with upgrades his damage increases, which is stated on your site/bot but the damage to leader is always stated as 22.

- Deckhand Butters has missing info for healing the leader, which is 10%, not full value.

5. Not sure if this problem is on your site or SPPD Stats but the values for damage and healing that is different for units and leader might be a bit wrong when it gets rounded down or up. To use examples i gave above, President Garrison and Deckhand Butters both deal full value to unit and 10% of that to the leader, but if the full value ends with a 5, it's rounded down by RedLynx, not up as it normally is. So a power that does 96-105 to a unit does 10 to the leader, 106-115 would do 11 to the leader. In most cases 105 would be rounded up to 11, but it's actually rounded down to 10.

6. I think that you should change the theme name from "General" to "Neutral" to match the name in the game, but that's just my opinion.

Anyway this are just the things i could think of at the moment. I've corrected a lot of information on my own Card Stats spreadsheet and i'm almost done fixing all of it. If you're missing some information from RedLynx or got it wrong i'll gladly share my info. Feel free to contact me on Discord. I'm Masked Ronin, i joined your Feinwaru Discord yesterday.

**Comment by MattheousDT** [comment]
@iTweeno @Umustalldie2 Could you guys have a look at the stats issues.

I can look into the 2nd issue

**Comment by MaskedRoninTTV** [comment]
- Powerfist Dougie power duration is 2 sec not 4.

- Pirateship Timmy's power deals full damage to main target and 50% as AOE.

- Zen Cartman's power range is 2.2, your site states it's 3.

- Unholy Combustion has wrong damage. At level 4 it says on your site that it does 46 damage, it actually does 48. Levels 5 and 6 are also 2 damage more than it says on your site. I don't have information for levels 1-3.

- Witch Garrison's power duration increases with levels, it's not always 10 sec like on your site.

- Dark Mage Craig gains power duration with upgrades, it's not always 6 sec.

- Summoned units like Mosquito Swarm also missing level 7 and have double level 3.

**Comment by MaskedRoninTTV** [comment]
- Medicine Woman Sharon, on your site it says that she heals leader for undefined amount. It's 10% of the unit heal, 5 is rounded down.

- Hookhand Clyde has static info for hitting leader, it's 10%.

**Comment by Dragon1320** [comment]
@MaskedRoninTTV when you're done making a list of all the stuff that still needs to be fixed from here and make those into separate issues, can you close this one?
