### ISSUE TITLE
Links do not have aria-label

### ISSUE THREAD

**Issue by MattheousDT** [feinwarusoftware/sppd#29]
![image.png](https://images.zenhubusercontent.com/5d4b5c4c1325bafe0671e8bc/ae12fa89-7b50-4200-80eb-d3912c77faf2)

For this, "go to home" would suffice. Please add to i18n as well.

**Comment by Dragon1320** [comment]
@iTweeno heres an explanation of this issue: **aria-label** is an **html attribute**. Please add said attribute to this image on the page (sppd logo), and set it to "go to home" or something to that effect.
![image](https://user-images.githubusercontent.com/18635887/63949491-69b40a00-ca72-11e9-89f1-9bf7dfaf4d0f.png)
You many need to google the bolded terms as well as how they work in **React**
