### ISSUE TITLE
Loading indicators

### ISSUE THREAD

**Issue by MattheousDT** [feinwarusoftware/sppd#42]
Add loading indicators to:
- [x] Search page result loading (First load and any filter change)
- [x] Search page load more
- [x] Card Page image and data

**Comment by MINIaMIDD** [comment]
![image](https://user-images.githubusercontent.com/43866054/64342412-5957de00-cfe2-11e9-9975-13b93b4ed28c.png) Little bug with the line between the rarity and theme when loading the card page
