### ISSUE TITLE
Spell and Trap type icons broken (web, bot)

### ISSUE THREAD

**Issue by MattheousDT** [feinwarusoftware/sppd#45]
- [ ] Type icons don't show up on the website card page at all
- [ ] Type icons are wrong on the bot

**Comment by iTweeno** [comment]
@MINIaMIDD Here's 2 examples of trap/spell cards. The difference is the icon at the top left of the card.
https://qa-sppd.feinwaru.com/TrapChomperCard
https://qa-sppd.feinwaru.com/SpellDynamiteCard
