### ISSUE TITLE
News section padding incorrect

### ISSUE THREAD

**Issue by MattheousDT** [feinwarusoftware/sppd#55]
![image.png](https://images.zenhubusercontent.com/5d4b5c4c1325bafe0671e8bc/582a309b-2d34-4d02-a018-813981e345fc)

Padding should be consistent, especially on the right side

**Comment by MattheousDT** [comment]
@Dragon1320 Fixed
![image.png](https://images.zenhubusercontent.com/5d4b5c4c1325bafe0671e8bc/b70d61e6-350f-4178-add5-a5ac788a5973)

**Comment by MINIaMIDD** [comment]
checked, changes approved
