### ISSUE TITLE
Language selector issues

### ISSUE THREAD

**Issue by MattheousDT** [feinwarusoftware/sppd#57]
- [x] Language selector goes to the left on text more than 2
![image.png](https://images.zenhubusercontent.com/5d4b5c4c1325bafe0671e8bc/777298fe-fc4a-4ed8-8b29-34c297117313)

- [x] Brazilian Portuguese translation has an ! on support us

**Comment by Dragon1320** [comment]
You didnt do the brazilian thing, just a thing in case you forget
