### ISSUE TITLE
Cards should have old padding when hover option is off

### ISSUE THREAD

**Issue by Dragon1320** [feinwarusoftware/sppd#89]
new:![image.png](https://images.zenhubusercontent.com/5d590b9a2aaf1f497cf97cfd/f31415ca-c30e-491e-850d-182cad5d37b4)

old:![image.png](https://images.zenhubusercontent.com/5d590b9a2aaf1f497cf97cfd/79cd93cf-0996-45f1-b9a8-9f862454866c)

There is no reason for that empty space to be there anymore and it looks better that way as well imo

**Comment by MattheousDT** [comment]
@Dragon1320 The reason for the new white space is because of the new card animation, and it needs to make sure that text that wraps onto multiple lines has enough space to move without hitting the cards below

**Comment by Dragon1320** [comment]
@MattheousDT ik, thats why i said that it should be removed **when the hover option is off**, cos in that case, there is no need for it
